# Generated by Django 4.2 on 2023-06-11 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom_drive", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "supermarket",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("shelve", models.CharField(max_length=255)),
                ("sub_department", models.CharField(max_length=255)),
                ("name", models.CharField(max_length=255)),
                ("quantities", models.CharField(blank=True, max_length=255, null=True)),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "price_per_quantity",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "quantity_unit",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("url_image", models.URLField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Supermarket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("supermarket", models.CharField(max_length=255)),
                ("department", models.CharField(max_length=255)),
                ("nom_drive", models.CharField(max_length=255)),
                ("city", models.CharField(max_length=255)),
            ],
        ),
    ]
