# Generated by Django 4.2 on 2023-06-18 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="product", name="quantities",),
        migrations.AddField(
            model_name="supermarket",
            name="adresse",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="supermarket",
            name="lattitude",
            field=models.DecimalField(decimal_places=7, max_digits=13, null=True),
        ),
        migrations.AddField(
            model_name="supermarket",
            name="longitude",
            field=models.DecimalField(decimal_places=7, max_digits=13, null=True),
        ),
    ]
