# Generated by Django 4.2 on 2023-07-12 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_remove_product_quantities_supermarket_adresse_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="supermarket", old_name="lattitude", new_name="latitude",
        ),
    ]
