# Generated by Django 4.2.3 on 2023-07-31 07:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0003_rename_lattitude_supermarket_latitude"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="nom_driveUrl",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="supermarket",
            name="nom_driveUrl",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
