# Generated by Django 4.2.3 on 2023-07-31 16:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0004_product_nom_driveurl_supermarket_nom_driveurl"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="name",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name="product",
            name="shelve",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="product",
            name="sub_department",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
