# Generated by Django 4.2.5 on 2023-09-24 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_supermarket_datescraped_alter_product_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='url_image',
            new_name='lien_image',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='name',
            new_name='nom_produit',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='price',
            new_name='prix_produit',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='price_per_quantity',
            new_name='prix_ratio',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='shelve',
            new_name='rayon_principal',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='sub_department',
            new_name='rayon_secondaire',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='quantity_unit',
            new_name='unite',
        ),
    ]
