# Generated by Django 4.2.5 on 2023-09-25 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_rename_url_image_product_lien_image_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'managed': False},
        ),
    ]
