# Generated by Django 4.2.5 on 2023-09-25 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_product_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='product',
            table='product',
        ),
    ]
