# Generated by Django 4.2.5 on 2023-09-28 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_product_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='supermarket',
            options={'managed': False},
        ),
    ]
