# Generated by Django 4.2.5 on 2023-09-28 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_supermarket_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='supermarket',
            options={},
        ),
    ]
