# Generated by Django 4.2.5 on 2023-09-28 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_supermarket_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='supermarket',
            name='lien_drive',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
