# Generated by Django 4.2.5 on 2023-09-28 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_supermarket_lien_drive'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supermarket',
            name='lien_drive',
        ),
    ]
