# Generated by Django 4.2.5 on 2023-09-28 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_remove_supermarket_lien_drive'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='supermarket',
            options={'managed': False},
        ),
    ]
